version: "1.0"

services:
  backend:
    build: ./backend
    ports:
    - "8080:8080"
    image: nathanmokh1/my-images:backend-v1.0
    env_file:
      - ./backend/.env
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    image: nathanmokh1/my-images:frontend-v1.0
    depends_on:
      - backend