version: "1.0"

services:
  backend:
    build: ./backend
    ports:
    - "8080:8080"
    volumes: 
    - ./backend:/app/backend
    env_file:
      - ./backend/.env
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
